### ISSUE TITLE
support react-native

### ISSUE THREAD

**Issue by xumoyan** [NoahZinsmeister/web3-react#171]
**Description**
I want to use web3-react core in a react-native project, what do I need to do
Can you provide an idea, let me realize it. Currently in use, it will report Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
**Additional Context**

**Comment by digital-flowers** [comment]
this issue is caused due to the difference between the `URL` object implementation between `react-native` and the `browser` that is used in this project, to fix this try the following:
1- run `yarn add react-native-url-polyfill/auto`
2- in the first line of `index.js` add the following line `import "react-native-url-polyfill/auto";`

Ggs :)
