### ISSUE TITLE
Detecting unsupported network

### ISSUE THREAD

**Issue by fvictorio** [NoahZinsmeister/web3-react#24]
What is the pattern for detecting that the user is connected to a network that is not one of the ids passed in `supportedNetworks` to `InjectedConnector`?

`context.error` has `Error: Unable to set any valid connector.`, that seems like a catch-all error.

Thanks!

**Comment by NoahZinsmeister** [comment]
hey @fvictorio, did you ever sort this out? the error type should be `UNSUPPORTED_NETWORK`, this generic error perhaps indicates another problem!

**Comment by clemlak** [comment]
Hey, I just encountered the same issue, instead of the `UNSUPPORTED_NETWORK` error, the `Unable to set any valid connector.` error showed up. My current workaround is to remove the `supportedNetworks` parameter and then check the current `networkId` inside the logic part of my component.
Obviously this is not the way things are supposed to work, so I'm going to investigate this to find the error.

**Comment by NoahZinsmeister** [comment]
hi all sorry to close this, but i'm working on the v6 release (which will be out soon), which handles errors much more robustly and will certainly solve this issue. in v6 it'll be possible to recognize errors with `instanceof` checks, which will be nice!
