### ISSUE TITLE
Multiple RPC URLs for WalletLinkConnector

### ISSUE THREAD

**Issue by dimitarnestorov** [NoahZinsmeister/web3-react#264]
**Description**

WalletLinkConnector has a `supportedChainIds` config property but only one RPC URL can be passed. In my opinion it should be possible to pass multiple RPC URLs just like with WalletConnectConnector.

**Comment by adriandelgg** [comment]
Agreed

**Comment by NoahZinsmeister** [comment]
yeah, this is a really weird usage pattern they're encouraging. confirmed with the team that the way it works is basically that url is only used if it's the user's first connection to the dapp, otherwise it's overridden with whatever chain the user is on. by the way, focusing dev efforts on v8 in the `main` branch going forward!
