### ISSUE TITLE
Guidance on NetworkOnlyConnector

### ISSUE THREAD

**Issue by PaulRBerg** [NoahZinsmeister/web3-react#35]
The docs are pretty straightforward, with the exception of `NetworkOnlyConnector`.

This is my context for `InjectedConnector` (MetaMask):

<img width="394" alt="InjectedConnector" src="https://user-images.githubusercontent.com/8782666/67626573-aa9f8380-f855-11e9-92a1-9b312f344b78.png">

And `NetworkOnlyConnector`:

<img width="394" alt="NetworkOnlyConnector" src="https://user-images.githubusercontent.com/8782666/67626587-d7ec3180-f855-11e9-934a-2c79e54e1759.png">

So I receive no account, but that's what I was expecting anyway.

It'd be nice to add more info in the docs about the most practical applications of `NetworkOnlyConnector`. I reckon that it works best in development, or when you just want to read data from the blockchain. But I'm not sure, since I see it's used in production at Uniswap.

**Comment by pcowgill** [comment]
@PaulRBerg My understanding is that it's used in production when you only want to read data from the blockchain. So Uniswap starts with the network-only connector (an ethers.js provider that doesn't have a "signer" yet pointing at Infura and Etherscan) before you log in to MetaMask. I think that's a good pattern for most web3 app to use.

**Comment by PaulRBerg** [comment]
Yes, this must be it. I agree it's a good pattern, but I think it would be very helpful to add more details about this in the docs.

Then, just a random thought, but wouldn't it make sense for this to be the default mode the library? That is, the `NetworkOnlyConnector` being the fallback connector, so developers don't have to orchestrate the logic between all other connectors and this.

**Comment by pcowgill** [comment]
@PaulRBerg Agreed that more docs on this would be useful - let's work on a PR for that. It appears that the [docs here](https://noahzinsmeister.gitbook.io/web3-react/v/latest/) are generated directly from [the README in this repo](https://github.com/NoahZinsmeister/web3-react/blob/latest/README.md) along with the other markdown files like [this one for custom connectors](https://github.com/NoahZinsmeister/web3-react/blob/latest/Custom-Connectors.md) and [this one for the exported connectors](https://github.com/NoahZinsmeister/web3-react/blob/latest/Connectors.md).

I think that would be a sensible default as long as there was a simple boolean to turn it off. A pretty common pattern for read-only access to Ethereum is querying indexed data with a subgraph on The Graph rather than hitting the blockchain more directly via Infura/Etherscan/Alchemy for this info, so leaving out `NetworkOnly` entirely should be easy if devs want that.

Your comments about sensible library defaults also inspired me to create [this related issue about the way Uniswap uses these connectors](https://github.com/NoahZinsmeister/web3-react/issues/46), and this would also mean less orchestration/boilerplate needed in order to benefit from these connectors.

**Comment by pcowgill** [comment]
I also note that given the naming of "network only", it implies that it should be used primarily when there's no account around to sign things.

But if we're interpreting "network only" just to mean that there's no third-party lib doing account management, there's still a pretty common pattern for dapps where there's an in-dapp ephemeral key generated with `ethers.js` that does the signing, and like with the current "network only" connector the dapp would connect directly to Infura/Etherscan/Alchemy.

So maybe in v6 there should be a new connector that is exported by default that's called `NetworkWithInDappSigner` and rename `NetworkOnly` to `NetworkReadOnly`. Maybe not those exact names, but you get the idea.

These different connectors might end up having different error codes that make sense.

**Comment by PaulRBerg** [comment]
Love all of your ideas.

> querying indexed data with a subgraph on The Graph ... so leaving out NetworkOnly entirely should be easy if devs want that.

I don't think the subgraph would overlap with the connector anyway.

**Comment by pcowgill** [comment]
Thanks!

Using only subgraphs for reading data implies that you wouldn't ever need a read-only connector. Unless there's some use case I'm not thinking of?

**Comment by PaulRBerg** [comment]
Well, there is always the use case of "community standards".

I followed how web3-react has been integrated in uniswap, and removing the NetworkOnlyConnector turned out to be a huge pain in the neck, because it had 2nd order effects I hadn't seen in advance.

But I suppose the v6 will implicitly solve this and make it easier to handle multiple connectors at the same time.

**Comment by NoahZinsmeister** [comment]
It's totally possible that the 'logged-out' view of a dApp could be sufficiently hydrated with data from e.g. a subgraph, that's a cool idea! In such cases of course you wouldn't need a `NetworkConnector`. The reason why we have one in Uniswap is because the data we need to show even a partially functioning UI to 'logged-out' users is most easily fetched directly from the chain with ethers via a remote RPC backend.

Up until now, the way that this was done was fairly hacky and unintuitive, but as you alluded to @PaulRBerg, v6 is natively multi-root, and Uniswap will [very shortly be migrating](https://github.com/Uniswap/uniswap-frontend/pull/514) to a multi-root setup with a persistent `NetworkConnector` and various account connectors.

**Comment by NoahZinsmeister** [comment]
@pcowgill I'm also still interested in the in-dapp private key idea! would probably be fairly trivial to extend the `NetworkConnector` with https://0x.org/docs/tools/subproviders#class-privatekeywalletsubprovider

**Comment by pcowgill** [comment]
@NoahZinsmeister Good to hear! Yeah either that or explicitly use the `ethers` signer and provider separately.
