### ISSUE TITLE
Misuse of the "hooks" name/concept

### ISSUE THREAD

**Issue by btraut** [NoahZinsmeister/web3-react#375]
Hello! I was excited to see the update to v8 beta, but after digging into the example, I'm pretty confused by the intended design.

Have you written anywhere why you chose a design where you need to pass the "hooks" around as props vs exposing data via context? Is there a plan to have a central controller (component) keep track of which connector the user has chosen and expose account/chain via context and actual hooks? Your connectors are fantastic, but I feel like there's a missing piece to the library.

Hooks, at least the way the React developers intended, should be globally accessible and not passed into a component. Custom hooks should be composed of primitive React hooks, and should they need to access external data, they should either access it directly or via context. Your design names functions as if they're hooks, but they really don't behave as such.

**Comment by NoahZinsmeister** [comment]
hey @btraut , thanks for flagging. a couple notes:

1. there's no actual need to pass the hooks around as props, this is more done for convenience in the example, so that most components can be made generic. in an applied setting, i imagine this looking a little different. for example, there might be a component for each connector type that uses the (statically accessible) hooks for that particular connector, with no need to pass around hooks as props. then, there might be a global hook (or hooks) which uses the hooks for _all_ connectors, selects amongst them according to some priority order, then returns the appropriate hooks/data. `useHighestPriorityConnector` is a somewhat primitive hint toward what this would look like in the generic setting, but as described in https://github.com/NoahZinsmeister/web3-react/issues/330 each application could write a specific version of this with the connectors they're using for increased legibility

2. while i agree it's a little odd, afaik there's no prohibition about passing hooks around as props. at the end of the day, they're just functions, no?

i hear your point though, perhaps it would be worth re-factoring the example so that all hooks are imported statically (probably each connector would have a component using the particular hooks for it, as returned from `initializeConnector`)? more than happy to do this if you think it would clarify things!

**Comment by btraut** [comment]
Thanks for the prompt response! I really appreciate it given the volume of issues you seem to get on this package.

1. The link to #330 is helpful -- looks like devs may want to figure out what that provider/meta-hook looks like and then perhaps integrate parts of that back into web3-react. I'll follow the discussion there.

2. One core concept of hooks is that they're unconditional and that they are associated with the calling component. Every single time you render a component, it should call exactly the same hooks in exactly the same order. When you pass in hooks as props, even if the child component calls them unconditionally, they actually belong to the parent (or grandparent or whoever actually initialized the connector) and it leaves it up to that decendant component to determine whether it's conditional or not -- there's a world where the decendant conditionally passes in a no-op vs one of your hooks, or worse yet, passes in a React primitive hook which would truly break rendering. Your design isn't invalid at all -- it's totally fine to pass callbacks/data accessors/whatever to a component, and it may even be the correct design to do so; they're just not truly hooks.

**Comment by NoahZinsmeister** [comment]
hmm yes i see your point. so perhaps we should shy away from encouraging passing these functions as props, and instead push explicit + static usage of the hooks.

i'm curious if https://github.com/NoahZinsmeister/web3-react/commit/17a5b74965ba5530245decf4a94765221e99a4c0 makes you feel better/is something that makes more sense to you?

**Comment by btraut** [comment]
Yeah, this feels like a better approach. There's still a few layers of abstraction I don't understand between core/store/etc and I look forward to more documentation and examples, but for now, I think you've arrived at better React principles.

**Comment by NoahZinsmeister** [comment]
cool, going to close this specific issue and work on some more docs/examples, but thanks for the feedback! don't hesitate to open another if anything comes up

you also might be interested in the new `getPriorityConnector` from core: https://github.com/NoahZinsmeister/web3-react/blob/0a4fb6cbb1d01e60e8f78c414716b71821a69f35/packages/core/src/index.ts#L35
