### ISSUE TITLE
deactivate metamask

### ISSUE THREAD

**Issue by loic001** [NoahZinsmeister/web3-react#377]
Hello,

Thanks for this new v8 which works better than v6!

How to deactivate/disconnect with metamask? looks like there is no deactivate function on the metamask connector

thanks

**Comment by cheshirrrcat** [comment]
@loic001 looking for the same
+1

**Comment by NoahZinsmeister** [comment]
thanks for flagging - so, afaik there's no way for an application to actually "disconnect" from metamask - that has to be user-initiated from inside the extension. however, what i've considered before is giving every connector a default `deactivate` function that simply clears the _web3-react state_, so that your UI can present a "disconnected" state after a user-initiated action. this function could be overridden for connectors that need to do more on deactivation (e.g. walletconnect). writing this up, i'm pretty convinced this is a good idea, will make a PR to try it out soon!

**Comment by loic001** [comment]
thanks! does it make sense to clean the store like this with setState ?

```
  const disconnect = () => {
    store.setState({ chainId: null, accounts: [] })

    // custom zustand action to clean the state
    setProvider({ provider: null })
    setAddress({ address: null })
    setActive({ active: false })
  }
```

**Comment by NoahZinsmeister** [comment]
ok, added this in https://github.com/NoahZinsmeister/web3-react/commit/fb8006876b37d95289abc3e13ccd033c1c6868bc and published, so if you bump your packages you should be able to `deactivate` now!

@loic001 to your question, could easily add a custom action for resetting the store, but for now i'm just calling `reportError(undefined)` which has the effect of resetting the store to its [default values](https://github.com/NoahZinsmeister/web3-react/blob/main/packages/store/src/index.ts#L32)

**Comment by loic001** [comment]
noted, thanks :)
