### ISSUE TITLE
Bundle size of beta version increased 

### ISSUE THREAD

**Issue by dohomi** [NoahZinsmeister/web3-react#395]
Hello

I use v6 at the moment and thought giving v8 a spin. I realised the bundle size went up pretty high, is this on purpose?

https://bundlephobia.com/package/@web3-react/core@8.0.9-beta.0

Thanks for your hard work on v8

**Comment by NoahZinsmeister** [comment]
good call-out @dohomi , the reason is the inclusion of `@ethersproject/providers`, which is used in the `useProvider` hook. my expectation is that most consumers of this library are going to be using ethers already, in which case this wouldn't actually incur a net bundle size hit

however, to better support non-ethers users, i've migrated `@ethersproject/providers` to an optionalDependency that is only loaded if that hook is rendered

does this address your concerns?

**Comment by dohomi** [comment]
@NoahZinsmeister I use mostly `ethers` directly, but sure this might make sense. How does this change affect `web3.js` users? Because I guess they use a different provider setup?

**Comment by NoahZinsmeister** [comment]
under the hood `ethers` just imports from the various `@ethersproject/*` dependencies, so yeah this won't actually effect your bundle, assuming of course that your `ethers` dependency matches the specified web3-react semver.

this change in theory shaves the `@ethersproject/providers` dependency from the bundle of `web3.js` users (god save them)

**Comment by dohomi** [comment]
@NoahZinsmeister haha I feel you, I trapped into the `web3.js` land mine as well once
