### ISSUE TITLE
Suggestion: Make selected connector hooks "connector" param optional

### ISSUE THREAD

**Issue by earthtojake** [NoahZinsmeister/web3-react#402]
In some cases a user might not be connected to a wallet so there is no `connector` argument to pass into the `getSelectedConnector` hooks. This makes things messy since hooks can't be conditional. Suggestion to make the `connector` argument optional and return undefined if it's not passed in, similar to the `provider` arg in `useENSName`.

My current workaround is to pass in a Network connector which we don't actually use: 

```
  // Hack to pass in a valid connector when wallet type is not set
  const connector = walletType != null ? getConnector(walletType) : networkConnector
  const isWalletConnector = !(connector instanceof W3Network)

  const _chainId = useSelectedChainId(connector)
  const chainId = isWalletConnector ? _chainId : undefined
  const _walletAddress = useSelectedAccount(connector)
  const walletAddress = isWalletConnector ? _walletAddress : undefined
  const accounts = useSelectedAccounts(connector)
  const _provider = useSelectedProvider(connector)
  const provider = isWalletConnector ? _provider : undefined
  const _ensName = useSelectedENSName(connector, provider) ?? undefined
  const ensName = isWalletConnector ? _ensName : undefined
  ...
```

More info: In our dapp design we use a raw JsonRpcProviders to query data, which makes it easy to develop with because we don't need to put hooks everywhere to access providers, they can just be accessed from the window, so we have no need for the Network connector.

**Comment by NoahZinsmeister** [comment]
interesting - so my concern with this is that returning `undefined` if no `connector` is passed will in some cases widen the return type - for example, `useSelectedIsActivating` would return `boolean | undefined` instead of just `boolean`.

i think what i'd recommend is passing in the `EMPTY` singleton from `@web3-react/empty`, that way you'll get the expected "non-active" return value for the hook(s) in question
