### ISSUE TITLE
WalletConnect reconnection after reloading page

### ISSUE THREAD

**Issue by w84april** [NoahZinsmeister/web3-react#419]
Hello everyone, is there any chance to handle if walletconnect connection already exists? Currently im using v6.2.10. I've seen necessary logic in other libraries, so I wonder if I could do the same:
![image](https://user-images.githubusercontent.com/32621609/153884587-a3057455-1829-4ca0-9337-e6a4783e4618.png)

Currently I can't see something that would help me to know if connection is established before activation:
![image](https://user-images.githubusercontent.com/32621609/153884913-e0ee16af-b50d-4469-8522-aedd22f504c6.png)

If there are any solutions of this case, please let me know

**Comment by NoahZinsmeister** [comment]
hi @w84april , the v8 walletconnect connector handles the case when the user is already connected! see e.g. https://github.com/NoahZinsmeister/web3-react/blob/main/packages/walletconnect/src/index.ts#L106 and https://github.com/NoahZinsmeister/web3-react/blob/main/packages/walletconnect/src/index.ts#L142

since v6 is being deprecated, i'm afraid it's unlikely that additional features will land related to this, though i'd be willing to accept bug fix PRs
