### ISSUE TITLE
V8 Seems completely broken on NextJS

### ISSUE THREAD

**Issue by jcbdev** [NoahZinsmeister/web3-react#427]
Trying out V8 on a nextjs I am having multiple issues which make v8 pretty much unusable.

The initial issues where based around the libraries use of mjs rather than cjs (I think another issue mentions this) and the only way to solve this was to add transpiling to next-js config, otherwise you have tons of issues importing zustand and it's associated libraries

```
const withTM = require('next-transpile-modules')([
  '@web3-react/core',
  '@web3-react/eip1193',
  '@web3-react/empty',
  '@web3-react/metamask',
  '@web3-react/network',
  '@web3-react/types',
  '@web3-react/url',
  '@web3-react/walletconnect',
  '@web3-react/walletlink',
]);
```

After getting past this is superficially appears to work but then on *restarting* a nextjs server you start getting issues with libraries accessing the global `window` (@metamask/detect-provider) object directly or `localstorage` (walletlink).

this happens when you import the initialisers so normally outside of any components you can use dynamic() import on:
```
import { initializeConnector, Web3ReactHooks } from '@web3-react/core';
import { Connector } from '@web3-react/types';
import { MetaMask } from '@web3-react/metamask';

export const [metaMask, hooks] = initializeConnector<Connector>(
  (actions) => new MetaMask(actions)
);
```

To work around this I tried loading in a useEffect hook to make these initialisations only occur on the client and using a dummy set of connectors (empty) on the server:
```
export default function useWeb3React() {
  const [hooks, setHooks] = useState<ReturnType<typeof getPriorityConnector>>(
    getPriorityConnector([network, networkHooks])
  );

  //Client side work around for metamask/walletlink accessing windows object directly
  useEffect(() => {
    let connectors = [];
    import('../connectors/metaMask').then(
      ({ hooks: metaMaskHooks, metaMask }) => {
        connectors.push([metaMask, metaMaskHooks]);
        import('../connectors/walletConnect').then(
          ({ hooks: walletConnectHooks, walletConnect }) => {
            connectors.push([walletConnect, walletConnectHooks]);
            connectors.push([network, networkHooks]);
            setHooks(getPriorityConnector(...connectors));
            console.log('loaded..');
          }
        );
      }
    );
  }, []);

  return useMemo(
    () => ({
      ...hooks,
    }),
    [hooks]
  );
}
```

But now there is another issue.  Because react tracks the use of hooks and how many times they are called between renders when you call `setHooks` to change the initialized hooks then because the hooks call other hooks internally. For example `usePriorityIsActivating()` wraps internal hooks it starts counting extra hooks for every connector that has been added

```
function usePriorityIsActivating() {
    return useSelectedIsActivating(usePriorityConnector())
  }
```
which calls:
```
function useSelectedIsActivating(connector: Connector) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const values = initializedConnectors.map(([, { useIsActivating }]) => useIsActivating())
    return values[getIndex(connector)]
  }
```

which as you can see now calls useIsActivating more times because of the more connectors.

I've used v6 on plenty of nextjs projects but this seems like a massive regression and it completely unusable.  I can see how you would not necessarily be able to fix external libraries referencing window or localstorage during SSR but the internal calls to hooks means you can only inititialize all connectors prior to first render.

**Comment by NoahZinsmeister** [comment]
hi @jcbdev, sorry you're having issues, and thanks for the report. i have a few thoughts!

first, i'm not quite sure why you (and seemingly others, based on e.g. #379) are having trouble with next.js. the example in this repo, which is also [hosted](https://web3-react-mu.vercel.app/), uses "vanilla" next.js with no problems, so i have to imagine it's just a config and/or version issue. have you tried running the example on localhost to verify that it works?

second, i hear you on SSR. previously, the example was using [`dynamic`](https://nextjs.org/docs/advanced-
features/dynamic-import#with-no-ssr) to force client-side rendering for all components that touched web3-react logic. the primary reason for this was because if the `connectEagerly` flag for a connector was set to true (which it previously was by default), connection attempts would be made on the server rendering pass, leading to either errors like `window` not being available, or hydration mismatches in content based on connection status. so, to address these issues i wrote and merged #431. what this PR did is make the `connectEagerly` argument for every connector default to false, instead of true. additionally, to preserve the _functionality_ of this argument (e.g. connecting to metamask on page load if it's unlocked, which i assume people still want), i've added an additional (optional) `connectEagerly` method to connectors that can be called inside a `useEffect` on mount (see e.g. https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example/components/connectors/MetaMaskCard.tsx#L23).

this should let you initialize all your connectors on the server without issue, and not have the hook mismatch issue described.

again, apologies for the issues you've run into, hoping that this explanation makes sense, and that the latest round of `beta` releases fix your issue! let me know, happy to continue working this out

**Comment by NoahZinsmeister** [comment]
this should be addressed in the latest `beta` packages, please open another issue if you're still having problems!

**Comment by nftgeek** [comment]
Hi @jcbdev  I'm also on the same page, were you able to use v8 in your Nextjs projects?  especially with SSR enabled.
