### ISSUE TITLE
How to use in Trust Wallet

### ISSUE THREAD

**Issue by corymsmith** [NoahZinsmeister/web3-react#9]
In the Readme it mentions Trust but I'm unclear on exactly what the connector would be, whether its just the Metamask one or what I should be doing...

**Comment by NoahZinsmeister** [comment]
Hi @corymsmith. Yeah, so I haven't actually done a lot of testing with Trust. In theory, it should be fully compatible with the MetaMask connector, because it uses the same injected web3 provider pattern. I'd recommend giving the MetaMask connector a try, and if anything doesn't work, feel free to file a bug report here and I can investigate!

**Comment by NoahZinsmeister** [comment]
Hey @corymsmith I generalized the former Metamask connector a bit, and it now fully supports Trust (and Tokenary!)! It's named `InjectedConnector`, and you can start using it now with `yarn add web3-react@unstable`, or wait for a stable release in a week or so! [The docs for this new version](https://noahzinsmeister.gitbook.io/web3-react/v/unstable/connectors#injectedconnector)

**Comment by kevinfaveri** [comment]
hey gm! what's the supposed way to do this now that the injectedconnector does not exists anymore?
